name: Deploy Angular App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Instalar dependências
        working-directory: ./frontend
        run: npm ci

      - name: Build do projeto Angular
        working-directory: ./frontend
        run: npm run build -- --configuration=production